name=EQSP32
version=1.5.1
author=Erqos Technologies info@erqos.com
maintainer=Erqos Technologies
sentence=A library for controlling your EQSP32 - ESP32 Industrial IoT Controller.
paragraph=This library provides the complete EQSP32 hardware and managed IoT APIs, including local and expansion I/O, MQTT integrations, and EQConnect provisioning.
category=Device Control
url=https://erqos.com/
architectures=esp32
precompiled=true
includes=EQSP32.h
